### ISSUE TITLE
ICA tutorial: wrong components (random seed?)

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3168] opened 2016-04-24 19:52 UTC
The ICA tutorial is a *bit* off.

![screen shot 2016-04-24 at 21 49 53](https://cloud.githubusercontent.com/assets/4321826/14770019/bdb267de-0a66-11e6-9250-8955bff46fa4.png)

![screen shot 2016-04-24 at 21 50 03](https://cloud.githubusercontent.com/assets/4321826/14770021/bf88cd32-0a66-11e6-91f7-91df130d875a.png)

I can't promise I can fix this for 0.12 ...

@dengemann

**Comment by dengemann** [comment] 2016-04-24 21:23
I will. No worries.

**Comment by jaeilepp** [comment] 2016-04-26 14:00
Fixed in https://github.com/mne-tools/mne-python/pull/3174. See if you agree.

**Comment by jona-sassenhagen** [comment] 2016-05-11 11:22
Oh oh ...

![bildschirmfoto 2016-05-11 um 13 20 21](https://cloud.githubusercontent.com/assets/4321826/15179332/4963dda0-177b-11e6-8cc1-ca01e58a7243.png)

I could take care of it eventually.

**Comment by jona-sassenhagen** [comment] 2016-05-11 11:22
@Eric89GXL reopen please :(

**Comment by Eric89GXL** [comment] 2016-05-11 11:53
This was recently fixed. Do you know the cause? Was there a regression,
errant commit, or is this example fragile? (Will reopen when I'm off mobile)

**Comment by dengemann** [comment] 2016-05-11 12:04
This is very weird indeed.

**Comment by Eric89GXL** [comment] 2016-05-11 14:02
Bisecting now...

**Comment by dengemann** [comment] 2016-05-11 14:05
the fun thing is that this got fixed 2 times at least.

**Comment by Eric89GXL** [comment] 2016-05-11 14:12
Found it -- @dengemann this commit makes things non-deterministic, which is funny since it's title is "fix seed issue in ICA tutorial":

https://github.com/mne-tools/mne-python/commit/4205bf09fec99067d4c5da667242146e01a10c94#diff-862a5a4a87f90baa4d64932537a53851R154

Notably, the `seed=` kwarg was removed in that commit :(

**Comment by Eric89GXL** [comment] 2016-05-11 14:16
... or rather, the "reference ICA" has no seed, so when (in that commit) it was switched from using the first of the section-based ICAs (which were deterministic) to the "reference ICA", it lost its deterministic-ness.

**Comment by Eric89GXL** [comment] 2016-05-11 14:17
In any case, I'm not sure of the proper fix here (seed the original, or go back to seeding the others and use the first one again), but I'm not surprised it's non-deterministic, because the random state isn't ever set. @dengemann can you fix it?

**Comment by dengemann** [comment] 2016-05-11 14:18
Ok I'll fix it once more. ... I hope for the last time.

**Comment by Eric89GXL** [comment] 2016-05-13 15:41
@dengemann will you have time for this soon, or should someone else have a look (@jona-sassenhagen maybe?)

**Comment by dengemann** [comment] 2016-05-14 16:45
I will have time on Monday for some MNE hacking.

**Comment by Eric89GXL** [comment] 2016-05-23 18:26
@dengemann it's been a while, any time for this one or should we get someone else on it?

**Closed** 2016-05-27 09:47 UTC
