### ISSUE TITLE
The MNE website is really slow to access from China

### ISSUE THREAD

**Issue by sakimarquis** [mne-tools/mne-python#8664] opened 2020-12-16 16:35 UTC
I don't whether this is a suitable problem to issue here. However, I can't find other ways to report this problem. The problem has last for a long time, and recently the speed is intolerably slow. I ask several friends to test from different regions in China, the problem persists. And when I access the MNE website by VPN, the speed improves a lot.

**Comment by agramfort** [comment] 2020-12-16 16:54
the website is hosted on github. You could mirror the website in china if
you want

>

**Comment by drammock** [comment] 2020-12-16 23:08
The problem is likely to be (at least partially) calls made to the Google API. We could consider ditching Google analytics, and see if we make any other Google API calls (we don't use Google fonts, at least)

**Comment by hoechenberger** [comment] 2020-12-17 00:05
> The problem is likely to be (at least partially) calls made to the Google API. We could consider ditching Google analytics, and see if we make any other Google API calls (we don't use Google fonts, at least)

The API calls are asynchronous, i.e. non-blocking. I suspect it's the JS source file that is loaded from Google's CDN. We could simply integrate it into our docs (i.e., serve it from GH pages). This should fix the issue.

**Comment by larsoner** [comment] 2020-12-17 00:22
@hoechenberger can you open a PR to integrate the JS file? I'm not sure how to keep it up to date. Maybe just a file in `_static` that we update as part of the release process?

**Comment by hoechenberger** [comment] 2020-12-17 08:38
> @hoechenberger can you open a PR to integrate the JS file? I'm not sure how to keep it up to date. Maybe just a file in `_static` that we update as part of the release process?

Yes, that'd be worth a shot. Or we actually set up a CI task that runs every night or once a week or so that retrieves the file and commits it to `master`.

**IF** that fixes @sakimarquis's issue.

**Comment by agramfort** [comment] 2020-12-17 10:36
let's check first it's the cause of the problem

>

**Comment by hoechenberger** [comment] 2020-12-17 14:32
@sakimarquis Does https://24173-1301584-gh.circle-artifacts.com/0/dev/index.html load any faster for you?

**Comment by sakimarquis** [comment] 2020-12-18 00:16
> @sakimarquis Does https://24173-1301584-gh.circle-artifacts.com/0/dev/index.html load any faster for you?

Unfortunately no. Overall they cost relatively same time for load the whole page. This result is tested in different browser and ISPs.

**Comment by larsoner** [comment] 2023-10-01 17:40
Closing in favor of https://github.com/mne-tools/mne-python/issues/11881 which I think is all we can do to try to fix this

**Closed by larsoner** 2023-10-01 17:40 UTC
Labels: DOC
