### ISSUE TITLE
IO of SSS info is broken after filtering with mne_process_raw

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#1823] opened 2015-02-22 18:12 UTC
To reproduce, take the somato data, filter with:

mne_process_raw --raw sef_raw_sss.fif --highpass 1 --lowpass 40 --save test_raw.fif --projoff --decim 2 --filtersize 16384

then try this:

```
import mne

info = mne.io.read_info('test_raw.fif')
mne.io.write_info('tmp_info.fif', info)
info = mne.io.read_info('tmp_info.fif')
```

it should break. In otherwords the MNE-C code breaks the Python IO of SSS metadata :( :(

@Eric89GXL bad weather in seattle?

**Comment by agramfort** [comment] 2015-02-22 18:29
@mshamalainen there is a bug in the writing of sparse matrices in the C code. The sparse matrix in maxfilter proc history gets messed up on writing back to disk.

can you have a look?

**Comment by BrainFPV** [comment] 2015-03-03 19:05
It was working in the 0.8 release.. bisecting now.

**Comment by mluessi** [comment] 2015-03-03 19:07
It was working in the 0.8 release, running bisect now.

**Comment by dengemann** [comment] 2015-03-03 19:07
> It was working in the 0.8 release, running bisect now.

I'm not sure I'm following, this functionality was recently added.

**Comment by Eric89GXL** [comment] 2015-03-03 19:08
0.8 didn't read the SSS info, now we do. @agramfort is implying the problem is with the C code, not the Python code.

**Comment by mluessi** [comment] 2015-03-03 19:10
Oh, I see.. makes sense. So the error only happens after running mne\_process\_raw, correct?

**Comment by mshamalainen** [comment] 2015-03-03 19:10
How did @agramfort <https://github.com/agramfort> come to that conclusion? What exactly happens as a manifestation of the problem? The C code seems to work flawlessly reading and writing sparse matrices.


> On Mar 3, 2015, at 2:08 PM, Eric Larson <notifications@github.com> wrote:
> 
> 0.8 didn't read the SSS info, now we do. @agramfort <https://github.com/agramfort> is implying the problem is with the C code, not the Python code.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/mne-tools/mne-python/issues/1823#issuecomment-77012058>.
> 



The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by mshamalainen** [comment] 2015-03-03 19:11
It does not happen to me even then.

> On Mar 3, 2015, at 2:10 PM, Martin Luessi <notifications@github.com> wrote:
> 
> Oh, I see.. makes sense. So the error only happens after running mne_process_raw, correct?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/mne-tools/mne-python/issues/1823#issuecomment-77012619>.
> 



The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by dengemann** [comment] 2015-03-03 19:13
@mluessi with @agramfort we processed data and realized that the fiff files containing SSS info are not readable anymore after the raw files have been processed using mne_process_raw + decimation. To be precise, the problem occured when evoked or epochs objects were created based on the processed raw files and saved to disk using python.

**Comment by dengemann** [comment] 2015-03-03 19:14
We were able to reproduce this using different SSSed datasets.

**Comment by mshamalainen** [comment] 2015-03-03 19:21
I believe now that this is the case but it is difficult to see how the C code would be broken in this respect. Let me investigate a little bit further.

> On Mar 3, 2015, at 2:14 PM, Denis A. Engemann <notifications@github.com> wrote:
> 
> We were able to reproduce this using different SSSed datasets.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/mne-tools/mne-python/issues/1823#issuecomment-77013274>.
> 



The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by agramfort** [comment] 2015-03-03 20:16
keep us posted @mshamalainen

**Comment by mshamalainen** [comment] 2015-03-03 20:18
There was, indeed, an error in the C code writing of sparse matrices. Fixed now. It was originally tested on my PowerPC MacBook and never came up because the C code never tried to actually use the sparse matrices it wrote. :)

**Comment by dengemann** [comment] 2015-03-03 20:19
@mshamalainen you rock! Thanks!!

**Comment by mluessi** [comment] 2015-03-03 20:20
I think it would make sense to also catch the error in the Python code and byte swapping in Python if it occurs. So it will work with raw files written by all versions of MNE. I volunteer to implement it.

**Comment by agramfort** [comment] 2015-03-03 20:25
PR more than welcome :)

**Comment by mshamalainen** [comment] 2015-03-03 20:27
This fix will be in the nightly build of MNE tomorrow.

**Comment by agramfort** [comment] 2015-03-03 21:09
mne-c.git clone up to date

**Comment by mluessi** [comment] 2015-03-03 21:21
There is a git clone of MNE-C? Where?

**Comment by agramfort** [comment] 2015-03-03 21:26
https://github.com/agramfort/mne-c

it's private though

**Comment by agramfort** [comment] 2015-03-03 21:31
btw if you want to take over the migration to git it would be great...

**Closed** 2015-03-04 01:21 UTC
