### ISSUE TITLE
add file like object support for raw file formats

### ISSUE THREAD

**Issue by rla3rd** [mne-tools/mne-python#9307] opened 2021-04-16 15:36 UTC
x-ref: https://mne.discourse.group/t/is-there-a-way-to-import-an-edf-file-represented-as-bytes/2997

#### Describe the new feature or enhancement
adding file like object support would allow using mne in spark through the use of its binaryfile method
https://spark.apache.org/docs/latest/sql-data-sources-binaryFile.html  the idea would be to load up the edfs into a binary file dataframe and then do a map function using bytes as input.  this would allow distributed loading of edfs in spark across the cluster,

#### Describe your proposed implementation
the existing method could be overriden with a named parameter such as file_like = True

#### Describe possible alternatives
could also create a 2nd method signature just for file like objects

**Comment by sappelhoff** [comment] 2021-06-28 11:24
seems related: https://github.com/mne-tools/mne-python/issues/8976

**Comment by larsoner** [comment] 2021-06-28 16:42
Indeed closing as a duplicate of #8976

**Closed by larsoner** 2021-06-28 16:42 UTC
Labels: ENH
