### ISSUE TITLE
raise self.failureException('<bound method Kit2FiffModel.<lambda> of <mne.gui._kit2fiff_gui.Kit2FiffModel object at 0x7f9e4df0cd10>> is not false')

### ISSUE THREAD

**Issue by ignatenkobrain** [mne-tools/mne-python#2581] opened 2015-10-30 20:57 UTC
``` python
======================================================================
FAIL: Test CombineMarkersModel Traits Model
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/mne-python-0.10/mne/utils.py", line 633, in dec
    return function(*args, **kwargs)
  File "/builddir/build/BUILD/mne-python-0.10/mne/gui/tests/test_kit2fiff_gui.py", line 35, in test_kit2fiff_model
    assert_false(model.can_save)
AssertionError: <bound method Kit2FiffModel.<lambda> of <mne.gui._kit2fiff_gui.Kit2FiffModel object at 0x7f9e4df0cd10>> is not false
    '<bound method Kit2FiffModel.<lambda> of <mne.gui._kit2fiff_gui.Kit2FiffModel object at 0x7f9e4df0cd10>> is not false' = self._formatMessage('<bound method Kit2FiffModel.<lambda> of <mne.gui._kit2fiff_gui.Kit2FiffModel object at 0x7f9e4df0cd10>> is not false', "%s is not false" % safe_repr(expr))
>>  raise self.failureException('<bound method Kit2FiffModel.<lambda> of <mne.gui._kit2fiff_gui.Kit2FiffModel object at 0x7f9e4df0cd10>> is not false')
```

**Comment by agramfort** [comment] 2015-10-31 09:19
ping @christianbrodbeck @teonlamont

**Comment by christianbrodbeck** [comment] 2015-10-31 13:18
OS, Traits version?

**Comment by ignatenkobrain** [comment] 2015-10-31 13:25
Fedora 24 (Rawhide), 4.5.0

**Comment by christianbrodbeck** [comment] 2015-10-31 13:38
I can't reproduce it on OS X and have no access to Fedora.

**Comment by ignatenkobrain** [comment] 2015-10-31 13:41
I can give you ssh to fedora after few hours.

**Comment by christianbrodbeck** [comment] 2015-10-31 14:02
Is somebody actually wanting to use kit2fiff with Fedora? Because the GUI probably has to be tested independently for platform dependent issues.

**Comment by Eric89GXL** [comment] 2017-03-21 15:05
@ignatenkobrain this hasn't seen action in a while. If you still have the problem with no workaround let us know. In the meantime I suspect the bug might be fixed by upstream libraries (e.g., tvtk).

**Closed by Eric89GXL** 2017-03-21 15:05 UTC
