### ISSUE TITLE
BUG: raw.plot_sensors(show=True) doesn't show figure

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#4261] opened 2017-05-11 21:43 UTC
raw.plot_sensors(show=True) doesn't show the figure as it should

**Comment by jaeilepp** [comment] 2017-05-12 08:20
I'm not able to reproduce this. Does ``plt.show`` make it appear?

**Comment by kingjr** [comment] 2017-05-12 13:53
Apparently, it plots the second time I call it, but not the first time:

```python
import mne
fname = mne.datasets.sample.data_path() + '/MEG/sample/sample_audvis_raw.fif'
raw = mne.io.Raw(fname)
```
```
Opening raw data file /home/jrking/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif...
    Read a total of 3 projection items:
        PCA-v1 (1 x 102)  idle
        PCA-v2 (1 x 102)  idle
        PCA-v3 (1 x 102)  idle
    Range : 25800 ... 192599 =     42.956 ...   320.670 secs
Ready.
Current compensation grade : 0
```
```python
raw.plot_sensors(show=True)
```

```
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Out[5]: <matplotlib.figure.Figure at 0x7f922f0bb410>
```

# no plot here

```python
raw.plot_sensors(show=True)
```

# plots

**Comment by Eric89GXL** [comment] 2017-05-31 15:39
Does this behavior change depending on which matplotlib backend you use?

**Comment by agramfort** [comment] 2017-07-22 12:53
I cannot replicate. Closing

**Closed by agramfort** 2017-07-22 12:53 UTC
