### ISSUE TITLE
Trouble with BDF stimulus channel (again)

### ISSUE THREAD

**Issue by nbara** [mne-tools/mne-python#5020] opened 2018-03-14 16:22 UTC
Hi all, 

Sorry for having to resuscitate this issue, but I'm having an issue with a BDF file (attached) with the latest MNE dev version. This file is a simple toy example with 8 channels and 16 time samples, with no `stim_channel`. The  file in question was saved using `pyedflib`.

When I do : 

```python
mne.io.read_raw_edf('eegfile.bdf', stim_channel='auto', preload=True)
```

I get (as expected) : 
`<RawEDF  |  eegfile.bdf, n_channels x n_times : 9 x 16 (15.0 sec), ~23 kB, data loaded>`

However when I do : 

```python
mne.io.read_raw_edf('eegfile.bdf', stim_channel=None, preload=True)
```

I get : 
`<RawEDF  |  eegfile.bdf, n_channels x n_times : 9 x 608 (16.0 sec), ~64 kB, data loaded>`

... which doesn't make sense. But shouldn't the output of read_raw_edf be the same in my case (no stimulus channel)

Do you have any idea why this could be ?

[eegfile.bdf.zip](https://github.com/mne-tools/mne-python/files/1811992/eegfile.bdf.zip)

**Comment by larsoner** [comment] 2018-03-14 16:25
Without looking at the data, yes I agree this looks broken.

**Comment by agramfort** [comment] 2018-03-14 20:03
@cbrnr can you have a look? thx

**Comment by cbrnr** [comment] 2018-03-14 20:36
Yes, there seems to be a problem with correctly detecting the sampling frequency. I'll try to hunt down the issue.

**Comment by cbrnr** [comment] 2018-03-14 21:18
On second look, this behavior makes sense. This file contains a stim channel with fs=38Hz, whereas the normal channels have fs=1Hz. If you load it with `stim_channel=None`, you're actually forcing `mne.io.read_raw_edf` to load the file in a wrong way, namely as if the last channel were a normal channel.

One thing I noticed though is that the stim channel is called "BDF Annotations", whereas we currently only check for "EDF Annotations" in our code. However, this is a separate issue and doesn't change the behavior if you explicitly set `stim_channel=None`.

**Comment by cbrnr** [comment] 2018-03-15 08:47
It might be useful to issue an info message whenever a special EDF+/BDF+ annotations channel is detected (these are channels called "EDF Annotations" or "BDF Annotations"). Furthermore, we could issue a warning if an annotation channel is detected, but the user loads the file with `stim_channel=None`. Or in the latter case, we could also exclude the stim channel completely (which would probably make more sense).

**Comment by nbara** [comment] 2018-03-15 08:52
@cbrnr Thanks a lot for checking this. I'm still not sure this is normal behaviour though as I'm never specifying any `stim_channel` when writing the file with pyEDFlib (my input data is 8 regular channels * 16 samples). Do you think it's a bug with pyEDFlib ?

I wonder if it makes sense to load a `stim_channel` (in my case `BDF annotations`) at a different sampling rate than regular channels). Either way, it's probably not a good idea to do it silently... What do you think ?

EDIT: just saw your last message, yes maybe this would be useful

**Comment by cbrnr** [comment] 2018-03-15 08:59
Apparently pyedflib automatically adds an annotation channel. I verified this with [SigViewer](https://github.com/cbrnr/sigviewer) - there are 8 channels and exactly one event at position 0, duration 0, type "Recording starts".

What's odd though is that even with `stim_channel="auto"` the annotations are not correctly parsed (the data in the last channel contains 16 zeros, and `find_edf_events()` returns nothing). This might have to do with the fact that we've never actually had a BDF+ file.

**Comment by cbrnr** [comment] 2018-03-15 09:04
Actually, now I'm not even sure if this is a valid BDF file since BioSig for MATLAB can't open it (I get an error related to a reshape command)...

**Comment by nbara** [comment] 2018-03-26 14:08
Sorry for the delay, I'll investigate this with my colleague and will let you know. From what I can tell though this file was simply written with pyEDFlib with no special parameters (and MNE can read it OK with the appropriate `stim_channel`).

**Comment by cbrnr** [comment] 2018-04-12 08:08
@nbara any update on this?

**Comment by cbrnr** [comment] 2018-04-13 10:27
@larsoner I think you can remove the 0.16 label since this is very likely not a bug.

**Comment by nbara** [comment] 2018-04-13 10:31
Sorry all, I have no time to properly investigate this at the moment. 

Why don't you close this issue for now and I'll reply here when I have more time on my hands to test it ?

**Comment by cbrnr** [comment] 2018-04-13 10:42
No problem @nbara - we can leave it open and just remove the 0.16 label so that this doesn't block the upcoming release.

**Comment by larsoner** [comment] 2018-11-05 20:14
@massich can you confirm that as soon as 0.17 is released we will get rid of all of the stim channel synthesis business? If so then please close this issue as it will become irrelevant immediately after release

**Comment by massich** [comment] 2018-11-06 17:36
yes. As soon as we release, we'll remove the stim channel synthesis

**Closed by massich** 2018-11-06 17:36 UTC
