### ISSUE TITLE
Incorrect montage view plotting only a subset of channels

### ISSUE THREAD

**Issue by stfnrpplngr** [mne-tools/mne-python#6273] opened 2019-05-06 11:35 UTC
#### Describe the bug
Plotting only a subset of the channels included in a Montage results in a corrupted plot.
@cbrnr probably related to this https://github.com/mne-tools/mne-python/pull/4276?

#### Steps and/or code to reproduce
```Python
import mne


montage = mne.channels.read_montage(
        kind='standard_1020', ch_names=['Fz', 'Cz', 'Pz'])
mne.viz.plot_montage(montage=montage)
```

#### Expected results
I would have expected a plot showing the positions of "Fz", "Cz" and "Pz"

#### Actual results
![issue_montage](https://user-images.githubusercontent.com/20129752/57222670-b9724f80-7003-11e9-86f5-0783d537bac8.png)

#### Additional information
Platform:      Windows-10-10.0.16299-SP0
Python:        3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
Executable:    C:\Continuum\anaconda3\pythonw.exe
CPU:           Intel64 Family 6 Model 142 Stepping 10, GenuineIntel: 8 cores
Memory:        15.9 GB

mne:           0.18.dev0
numpy:         1.16.2 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.2.1
matplotlib:    3.0.3 {backend=Qt5Agg}

sklearn:       0.20.3
nibabel:       Not found
mayavi:        Not found
cupy:          Not found
pandas:        0.24.2
dipy:          Not found

**Comment by larsoner** [comment] 2019-05-06 15:42
Thanks for the report -- closing as duplicate of #5190 and #3987. Proposal for fixing [here](https://github.com/mne-tools/mne-python/issues/3987#issuecomment-298920228) and WIP PR in #5472, feel free to take over if possible!

**Closed by larsoner** 2019-05-06 15:42 UTC
