### ISSUE TITLE
Shift-arrow keys not working on linux with remote X11

### ISSUE THREAD

**Issue by dgfitch** [mne-tools/mne-python#7323] opened 2020-02-14 15:48 UTC
#### Describe the bug
Shift-arrow keys do not scroll by 100% window width on certain Linux/X11 systems.

#### Steps to reproduce
Load up any sample data set and do `raw.plot()`:

    import mne
    from mne.datasets import sample
    data_path = sample.data_path()
    fname = data_path + '/MEG/sample/sample_audvis_raw.fif'
    raw = mne.io.read_raw_fif(fname)
    raw.plot()

Press Right arrow. Hold shift and press right arrow. 

#### Expected results
We expect [from the docs](https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw.plot) to scroll by 100% of window width with Shift down

#### Actual results
It only scrolls a 20% chunk like the arrow key by itself

#### Additional information
This is only happening on certain systems, when remotely accessing via X11. Shift-arrow is working fine on my local Ubuntu test.

I understand that this being system-specific is problematic, but I would like to help track down what's happening...

Platform:      Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-redhat-7.7-Nitrogen
Python:        3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]
Executable:    /study/edit/apps/conda3.7/bin/python
CPU:           x86_64: 48 cores
Memory:        Unavailable (requires "psutil" package)
mne:           0.19.2
numpy:         1.18.1 {blas=openblas, lapack=openblas}
scipy:         1.4.1
matplotlib:    3.1.2 {backend=TkAgg}

sklearn:       0.22.1
numba:         Not found
nibabel:       Not found
cupy:          Not found
pandas:        0.25.3
dipy:          Not found
mayavi:        Not found
pyvista:       Not found
vtk:           Not found

Here's some `xev` output to confirm the keys appear to be working normally. I don't know enough about matplotlib and keyboard events to debug further yet...

> KeyPress event, serial 34, synthetic NO, window 0x6c00001,                                                      
>     root 0x138, subw 0x0, time 1585209, (89,56), root:(1920,1059),
>     state 0x10, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,                                           
>     XLookupString gives 0 bytes:                                                                                
>     XmbLookupString gives 0 bytes:                                                                              
>     XFilterEvent returns: False                                                                                 
>                                                                                                                 
> KeyPress event, serial 37, synthetic NO, window 0x6c00001,                                                      
>     root 0x138, subw 0x0, time 1585869, (89,56), root:(1920,1059),                                              
>     state 0x11, keycode 114 (keysym 0xff53, Right), same_screen YES,
>     XLookupString gives 0 bytes:                                                                                
>     XmbLookupString gives 0 bytes:                                                                              
>     XFilterEvent returns: False                                                                                 
>                                                                                                                 
> KeyRelease event, serial 37, synthetic NO, window 0x6c00001,                                                    
>     root 0x138, subw 0x0, time 1585971, (89,56), root:(1920,1059),                                              
>     state 0x11, keycode 114 (keysym 0xff53, Right), same_screen YES,                                            
>     XLookupString gives 0 bytes:                                                                                
>     XFilterEvent returns: False                                                                                 
>                                                                                                                 
> KeyRelease event, serial 37, synthetic NO, window 0x6c00001,                                                    
>     root 0x138, subw 0x0, time 1586444, (89,56), root:(1920,1059), 
>     state 0x11, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,                                           
>     XLookupString gives 0 bytes:                                                                                
>     XFilterEvent returns: False

**Comment by larsoner** [comment] 2020-03-04 15:27
> This is only happening on certain systems, when remotely accessing via X11. Shift-arrow is working fine on my local Ubuntu test.
>
> I understand that this being system-specific is problematic, but I would like to help track down what's happening...

The first step is to see if any other software that uses shift-interaction detects the shift properly. If it does, then it's a Python (probably matplotlib) problem. If it doesn't, its an X.org problem.

Feel free to continue posting and people can respond if they have other ideas, but I'm going to close the issue since it's not a bug with MNE itself.

**Closed by larsoner** 2020-03-04 15:27 UTC
