### ISSUE TITLE
bug when pick_ori="normal" and loose=1?

### ISSUE THREAD

**Issue by adykstra** [mne-tools/mne-python#4323] opened 2017-06-16 12:57 UTC
Should the upper bound of the following inequality (line 667 in inverse.py) be inclusive?

`is_loose = 0 < inv['orient_prior']['data'][0] < 1`

**Comment by joewalter** [comment] 2017-06-16 14:17
The problem is that with `loose = 1` we don't rotate the coordinate system. So if you used a forward operator with non-surface oriented local coordinate systems to construct your inverse then picking normal won't work. As an alternative we could decide to always rotate the coordinate system if loose is not `None`. I could add that in #4312. However this is dangerous when working with more that one source space including volume or discrete. We definitely need to check the applicability of the input parameters depending on the type of source space.

**Comment by Eric89GXL** [comment] 2017-06-16 15:17
> As an alternative we could decide to always rotate the coordinate system if loose is not None. I could add that in #4312. However this is dangerous when working with more that one source space including volume or discrete.

Yes I would say always rotate if loose is not None.

I don't see how there is any problem with vol/discrete source spaces if we say that `loose` only applies to surface source spaces...?

**Comment by agramfort** [comment] 2017-06-16 15:22
+1 to rotate if loose is not None

**Comment by Eric89GXL** [comment] 2017-06-16 15:33
@agramfort is there a good reason why we don't always rotate to surf ori for surfaces?

**Comment by joewalter** [comment] 2017-06-16 15:44
@Eric89GXL I see no problem, if we do not allow picking normal at all if there are non-surface source spaces. If picking normal. However if we allow it, then I think the line `is_loose = 0 < inv['orient_prior']['data'][0] < 1` is dangerous as it depends on the order of the src in the forward (e.g. inv['orient_prior']['data'][0] is not the loose value if the first src in the forward model is a volume).

**Comment by Eric89GXL** [comment] 2017-06-16 15:45
> e.g. inv['orient_prior']['data'][0] is not the loose value if the first src in the forward model is a volume).

Why? Can't we make `inv['orient_prior']` always be the orient prior for the surface source spaces?

**Comment by agramfort** [comment] 2017-06-16 16:11
> @agramfort is there a good reason why we don't always rotate to surf ori for surfaces?

Not always needed but i don't a real usecase

**Comment by joewalter** [comment] 2017-06-16 16:15
Isn't inv['orient_prior']['data'] just the orient_prior computed in compute_orient_prior?

**Comment by Eric89GXL** [comment] 2017-06-16 16:27
I don't know without looking at the code, I believe you that it is.

In any case, can we do something better than just using `inv['orient_prior']['data'][0]` to alleviate your concern / the potential danger? I don't quite see the blocker here, maybe some code snippets / use cases would help.

**Comment by joewalter** [comment] 2017-06-16 18:02
Using the minimum should be enough

**Comment by larsoner** [comment] 2021-02-19 18:57
Looking at the code more recently, I think we're stuck with our existing convention of `< 1` rather than `<=1` for backward compat purposes so I'll close this

**Closed by larsoner** 2021-02-19 18:57 UTC
