### ISSUE TITLE
BUG: dipole plot invalid show param 

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#4211] opened 2017-04-19 21:34 UTC
`dip.plot_amplitudes(show=True)`

doesn't show. We need to add `plt.show()` to show the figure.

**Comment by Eric89GXL** [comment] 2017-04-19 22:20
Can you make a PR?

**Comment by agramfort** [comment] 2017-07-21 11:52
@massich maybe this is an easy one to get started

**Comment by massich** [comment] 2017-07-25 16:57
@kingjr I can't reproduce the error. 
```py
import os.path as op
from mne import read_dipole
from mne.datasets import testing
data_path = testing.data_path(download=True)
dip_fname = op.join(data_path, 'MEG', 'sample', 'sample_audvis_trunc_set1.dip')
dipoles = read_dipole(dip_fname)
dipoles.plot_amplitudes()
```
generates a picture for me.

**Comment by agramfort** [comment] 2017-08-03 14:24
we cannot replicate. Closing

**Closed by agramfort** 2017-08-03 14:24 UTC
