### ISSUE TITLE
CI, MAINT: pip install failures

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#8591] opened 2020-12-02 00:24 UTC
pip is trying and failing to compile `llvmlite` from source on the Azure windows tests ([see here](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=10488&view=logs&j=8d04c17d-3f6b-5313-febd-debdd8b57f4c&t=3680e94e-d3c2-55c5-2f66-41608de01c92&l=423)).  It is also complaining about "falling back to setup.py because of missing wheels package" [see here](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=10488&view=logs&j=8d04c17d-3f6b-5313-febd-debdd8b57f4c&t=3680e94e-d3c2-55c5-2f66-41608de01c92&l=395).  Maybe adding "wheels" will fix it?  This may be related to the new pip dependency resolver, which just became default in pip 20.3 yesterday... we could also try rolling back to use the old resolver.

**Comment by cbrnr** [comment] 2020-12-02 07:46
Can anyone on Windows reproduce this? I had a similar issue on macOS, pip didn't find wheel and fell back to source packages because most (all) binary macOS wheels have `10_9` in their name, and pip deemed the new macOS release (11) to be incompatible. However, this behavior has been fixed with pip 20.3.

**Closed** 2020-12-02 16:40 UTC
Labels: BUG
