### ISSUE TITLE
 Different data and plots when reading the same edf file in mne, eeglab and edfbrowser

### ISSUE THREAD

**Issue by datalw** [mne-tools/mne-python#11468] opened 2023-02-11 08:58 UTC
Hi,
I was informed on discourse that I should open an issue concerning this problem, since this is a bug in mne. 
Please see the details of the problem [here](https://mne.discourse.group/t/different-data-and-plots-when-reading-the-same-edf-file-in-mne-eeglab-and-edfbrowser/6318).
A related issue is [here](https://github.com/mne-tools/mne-python/issues/10635).

**Comment by agramfort** [comment] 2023-02-11 10:15
closing as duplicate of https://github.com/mne-tools/mne-python/issues/10635

thanks @datalw 

yes we should fix this...

**Closed by agramfort** 2023-02-11 10:15 UTC
