### ISSUE TITLE
FIX/DOC: Documentation

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1495] opened 2014-08-06 10:55 UTC
Dear all. I feel over the next release cycle we should chose improving our documentation as a main goal. I know most of us including myself find it more rewarding to add new code. But we must bite that bullet, I feel. If we distribute efforts a bit and get well organized it might be less of a pain. 
And importantly, as a project, we'll be making more progress if newcomers find it easy to get started. 

This includes at least the following points:
- ~~make more explicit that small examples are actually API examples and shall not be taken too literally (e.g. prevent users from adding random noise-arrays to threir data when doing using spatio-temporal clustering, etc.)~~ #6694 adds a warning to the top of the examples gallery
- disseminate slide shows, screen casts
- send a user poll to the mailing list
- ~~reorganize examples (e.g. order by intent and processing-step)~~ #2101
- ~~add real tutorials with stronger commitment to the wording / the recommendations~~ #3101
- ~~merge MNE manual with MNE-Python docs~~

Help users with pitfalls:
- ~~Starting with Python~~ (#3265): #6694 adds an updated "getting started with python" page.
- the use of Montage
- ~~working with a template brain~~ [this exists now](https://mne.tools/dev/auto_tutorials/source-modeling/plot_eeg_no_mri.html)
- `n_jobs=1` to save memory
- freesurfer + source space API, vertex indices, vertex numbers (#3465)
- morphing and missing vertices (#4034)
- ~~basic Python issues (e.g., paths #2052)~~
- ~~+/- in Evoked~~
- ~~integrate IPython notebooks?~~
- ~~coversion between float32 and float64 data on read/write (https://github.com/mne-tools/mne-python/issues/2720)~~

"Migrating to / working with" section:
- Xfit / Xplotter (@Eric89GXL)
- FieldTrip (#3362)
- ~~EEGLAB (@jona-sassenhagen?): explaining the distinction in channel types etc.~~

Bug reports (from @dengemann):

Set up list of things to check + rule out before filing a bug report, inspired by https://github.com/mxcl/homebrew/wiki/Troubleshooting

Extended tutorials:
- epochs selection and event handling (see #1963)
- ~~artefact removal~~ These have been expanded / overhauled by @drammock
- group statistics (make explicit 2 (spatial / no spatial prior) X 2 (F/T-test) API, clarify TFCE (it's not another test, but an enhancement method)), clarify that despite t-test inputs, spatio-temporal permutation clustering is not parametric and alos it does not give a multiple comparison corrected t-map, which means it's not just a thresholding to a parametric stat. Also add recent insights on decoding stats. Discuss repeated measure designs and options (hierarchial subtraction with t-test, rANOVA, etc.)
- coreg (#3358)

Manual:
- time-frequency module: tfr functions vs. psd functions
- ~~saving objects to disk (we discuss reading but not saving/writing ...)~~ *many tutorials now include this*
- transformations (#3465)
- ~~decoding section explaining how the API follows the sklearn convention. Subsections for spatial pattern methods & time gen + time decoding~~

For devs:
- cookbook like [this](http://pandas.pydata.org/pandas-docs/dev/cookbook.html) with common idioms, one liners

cc @teonlamont @christianbrodbeck @mainakjas @rgoj @dgwakeman @adykstra @legitta @deep-introspection @olaf @mshamalainen @mluessi  @Eric89GXL  @agramfort ... and and and ...

**Comment by Eric89GXL** [comment] 2015-04-19 22:04
Moving this to 0.10 unless @agramfort can convince someone to dedicate the hours

**Comment by dengemann** [comment] 2015-04-19 22:06
@Eric89GXL let's keep this for rainy summer days in Seattle or so.

**Comment by jasmainak** [comment] 2015-12-09 01:26
I had to look at the EEGLAB documentation while I was working on my PR https://github.com/mne-tools/mne-python/pull/2676. If I can have @agramfort 's blessing at some point, I could revamp the documentation a bit. I think it needs some love. More text, less code, more screenshots, and walking through everything step-by-step. I also see missing pages on the manual: http://martinos.org/mne/stable/manual/preprocessing/filter.html and http://martinos.org/mne/stable/manual/preprocessing/bads.html. If I was a user, I would see this as a bad sign and wouldn't use the software just seeing this.

**Comment by Eric89GXL** [comment] 2015-12-09 01:35
It would be great if you had time to work on it, there's quite a list at the top to work with. Feel free to add items.

**Comment by agramfort** [comment] 2015-12-09 14:23
+1e4 !

**Comment by jona-sassenhagen** [comment] 2015-12-16 08:22
@dengemann what format do you mean wrt. EEGLAB conversion? A wiki or something like that? iPython notebook, wiki style, ...?

One thing (different thing) I would like to see, and would be willing to write, is a more extended example of how to get from raw files to a simple full analysis, including group statistics, for the most simple thing EEG/ERP guys will think of: just two conditions, import, data cleaning, ERP plotting, stats. Preferably just an iPython notebook.

**Comment by agramfort** [comment] 2015-12-16 08:30
what have now tutorials in mne using block execution of sphinx-gallery

see for example:

https://github.com/mne-tools/mne-python/blob/master/tutorials/plot_creating_data_structures.py

but it can be a notebook / blog post to start.

**Comment by deep-introspection** [comment] 2015-12-16 08:46
+1 for the notebook format!

**Comment by agramfort** [comment] 2015-12-16 09:03
FYI sphinx-gallery will offer a notebook download link even if the file you
write is a plain py file in the version control system.

**Comment by jona-sassenhagen** [comment] 2015-12-16 09:08
I'll write a sphinx example for group-level traditional ERP analysis okay?

For the caveats-when-migrating-from-EEGLAB thing, wiki format seems more appropriate ...

**Comment by agramfort** [comment] 2015-12-16 09:14
>
> I'll write a sphinx example for group-level traditional ERP analysis okay?
>

yes but what data do you plan to use? it must be available as a dataset.


> For the caveats-when-migrating-from-EEGLAB thing, wiki format seems more
> appropriate ...
>

rst + github offers almost the same as a wiki. You can directly edit on
github.

**Comment by jasmainak** [comment] 2015-12-16 10:36
@jona-sassenhagen : what would be really cool is to have a table like this: http://mathesaurus.sourceforge.net/matlab-numpy.html with roughly equivalent functions in the same row along with cross-refs. It should be easy to do and would be super-useful for anyone migrating. Wdyt? +1 for  a _simple_ tutorial .. please don't make it too complicated.

**Comment by jona-sassenhagen** [comment] 2015-12-16 10:45
I could share 3 or 5 or so downsampled files from my brain and language paper, which was a very simple experiment, and show how to basically reproduce the analysis up to the plots (too lazy to do the single-trial stats). I'll also think about an eeglab-to-mne table, although, while this a cool idea in principle, a lot of this is not about stuff with clearly equivalent functions due to the object oriented nature of mne vs eeglab's matlab style. 
Won't come around to the files before xmas though.

**Comment by Eric89GXL** [comment] 2015-12-16 14:02
@jona-sassenhagen I actually edited the post to tag you. The idea I had in mind was to include whatever you think would be useful to help EEGLAB users transition to or work with mne-python. A table could work, or just a few paragraphs about major things to think about (object oriented vs not, channel types vs all EEG, etc.). More work on a complete pipeline also sounds cool as a complementary bit in another section.

**Comment by jona-sassenhagen** [comment] 2015-12-16 14:05
Yup, I've already written up a lot of this.

**Comment by jasmainak** [comment] 2015-12-16 14:24
@jona-sassenhagen : don't hesitate to make a PR early

**Comment by Eric89GXL** [comment] 2016-02-18 18:31
FYI I am thinking of revamping the installation page to look more like this:

http://nilearn.github.io/introduction.html#installing-nilearn

**Comment by agramfort** [comment] 2016-02-19 10:23
yeah !

**Comment by kingjr** [comment] 2016-03-17 02:52
I'm getting a bit confused where I should find info between the manual, examples, tutorials & faq. How about we restrict the FAQ to non-scientific questions (i.e. not covariance, or inverse modeling), and focus on classic setup, i/o, memory, speed & bugs issues?

**Comment by choldgraf** [comment] 2016-10-26 18:23
Hey all - just FYI we decided to host a "docathon" at BIDS this coming January. It'll be a weeklong (ish) event that is hackathon-style, but focused on improving documentation and tools for documentation. We'll have folks meeting at Berkeley, but we'll hopefully have a good remote contingent as well (at the very least there are folks at the data science centers of UW and NYU interested).

Just putting this here in case we can come up with a todo list for that event and get some interest from the MNE community.

https://github.com/BIDS/docathon

**Comment by Eric89GXL** [comment] 2016-10-26 18:25
Let me / us know when you have some dates and times finalized and I'll try to block off some time to work remotely

**Comment by choldgraf** [comment] 2016-10-26 18:34
Cool - it'll be roughly January 27th, planned to last about a week. We'll probably have one joint meeting at the start to assign projects / get people up to speed (maybe have some tutorials and demos, etc), and then some short checkups throughout (or at the end of) the week. So plenty of time for independent working...

**Comment by agramfort** [comment] 2017-07-22 12:14
@dengemann please update this issue and eventually close it

**Comment by larsoner** [comment] 2021-02-19 17:58
Closing for #6794

**Closed by larsoner** 2021-02-19 17:58 UTC
Labels: DOC
