### ISSUE TITLE
adding support to import files obtained with older NIRx versions 

### ISSUE THREAD

**Issue by mlrocca** [mne-tools/mne-python#10156] opened 2021-12-20 15:54 UTC
#### Describe the new feature or enhancement
*Please provide a clear and concise description of what you want to add or
change.*

Could you add support for older NIRx versions?

We used a continuous wave NIRS system (NIRSport 8X8, Nirx Medical Technologies LLC, Berlin, Germany). The fNIRS data acquisition software was the NIRStar 14.2 (Version 14, Revision 2, Release Build, 2016-04-15 NIRx Medizintechnik GmbH, Berlin, Germany; www.nirx.net).

Currently, we are not able to import our fNIRS file in MNE.

#### Describe your proposed implementation
*Describe how you think the feature or improvement should be implemented (e.g., 
as a new method on an existing class? as new capability added to an existing
method?) If you're not sure, please delete this section and the next section.*

#### Describe possible alternatives
*If you've suggested an implementation above, list here any alternative
implementations you can think of, and brief comments explaining why the chosen
implementation is better.*

#### Additional comments
*Add any other context or screenshots about the feature request here.*

**Comment by drammock** [comment] 2021-12-20 16:09
closing as duplicate of #10147.  I will edit that one to make it more clear that it's a feature request and not a question.

**Closed by drammock** 2021-12-20 16:09 UTC
Labels: ENH
