### ISSUE TITLE
[Feature request]: add to_data_frame() function to EpochsTFR

### ISSUE THREAD

**Issue by justinf2** [mne-tools/mne-python#6619] opened 2019-07-31 19:27 UTC
I would be great to be able to generate a pandas data frame from a EpochsTFR object like one can from an Epochs object, but with an extra index value for the frequencies.

**Comment by agramfort** [comment] 2019-08-01 08:24
can you share a code snippet that would do this or even send a PR? how
would indexing work as data are naturally 3d?

**Comment by justinf2** [comment] 2019-08-01 19:01
Sure. Let me take a look at implementing something and get back to you. Perhaps I am completely thinking about this in the wrong manner. Thanks for the quick response!

**Comment by drammock** [comment] 2021-03-16 15:17
closing as duplicate of #7975

**Closed by drammock** 2021-03-16 15:17 UTC
