### ISSUE TITLE
add_channels causes duplication in info['hpi_results'] and info['hpi_meas']

### ISSUE THREAD

**Issue by sarasommariva** [mne-tools/mne-python#5200] opened 2018-05-11 13:38 UTC
Hi, 

I think I found a small bug in the function `add_channels`.
When modifying an  existing data some of the fields (at least, `‘hpi_results’` and `‘hpi_meas’`) are duplicated causing some compatibility problems with e.g. neuromag.
Looking into the code, I think the problem is in the function `_merge_dict_values` . Both `‘hpi_results’` and `'hpi_meas’` consist of a list of dictionaries that seem to be concatenated by the function.

Here is a minimum example that demonstrates the issue:

https://gist.github.com/sarasommariva/d1c4b1a3015bf3ae33fefc4ffef2cbc9

**Comment by agramfort** [comment] 2018-05-14 08:55
I can confirm this unexpected behavior.

@larsoner you wrote this code I think. thoughts?

**Comment by larsoner** [comment] 2018-05-14 11:56
Yes these should not be duplicated, but rather checked to make sure they are consistent (assuming both instances have them, it's probably fine if one does and the other does not), throwing an error if they are not consistent.

**Comment by agramfort** [comment] 2018-05-14 12:36
+1

@sarasommariva can you give it a try?

**Comment by larsoner** [comment] 2018-05-14 15:05
That sounds about right. You can use `object_diff` before calling `_merge_dict_values` if you want

**Comment by larsoner** [comment] 2021-02-19 18:48
Looks like this was fixed by @sarasommariva in #5211 (thanks!)

**Closed by larsoner** 2021-02-19 18:48 UTC
Labels: BUG
