### ISSUE TITLE
bug in mne_browse_epochs

### ISSUE THREAD

**Issue by mainakjas** [mne-tools/mne-python#2324] opened 2015-07-21 13:15 UTC
@jaeilepp if I click on the lower right corner of the epochs browser (below the scroll bar), I get an error which says:

```py
In [2]: Floating point exception
```
Ipython closes and everything crashes. Maybe I should do more science to discover such corner cases ;)

**Comment by mainakjas** [comment] 2015-07-21 13:27
I think the scrollbar has to be at the bottommost position for this error to occur. So, scroll to the bottom and then click on the bottom left corner. @yousrabk couldn't reproduce this on her computer but I can reproduce it on the example. If anyone else can reproduce it, maybe that's useful info

**Comment by jaeilepp** [comment] 2015-07-24 06:47
I can't reproduce.

**Comment by mainakjas** [comment] 2015-10-02 12:50
I can show you on my computer :)

**Comment by Eric89GXL** [comment] 2015-11-25 14:04
@jasmainak you still having this issue?

**Comment by jasmainak** [comment] 2015-11-25 14:07
yes, this is not fixed and @jaeilepp has been able to reproduce it on my computer

**Comment by jaeilepp** [comment] 2016-06-23 08:53
This is solved. Closing...

**Closed by jaeilepp** 2016-06-23 08:53 UTC
