### ISSUE TITLE
TFRaverage.plot() only plots the data from the first channel when 'picks=' is a sensor type or a list of sensors. 

### ISSUE THREAD

**Issue by AaronAngJW** [mne-tools/mne-python#9322] opened 2021-04-20 08:17 UTC
#### Describe the bug
As with the title, `TFRaverage.plot()` does not plot the averaged activity across all sensors when multiple sensors were selected. Instead, it plots the activity of only the sensor with the smallest ID/number provided in `'picks='`

#### Steps to reproduce
Please refer to the follow discussion on https://mne.discourse.group/t/plotting-of-mne-combine-evoked-output-based-on-averagetfr-input-mutiple-channels-only-shows-tfr-output-of-the-first-channel/3008/8

#### Expected results
For my analysis, I was hoping to attain just one plot of the averaged TFR output off a list of selected sensors. (eg. activity across all sensors selected would be averaged into one time-frequency plot.)

#### Additional information
Currently, this does not work with mne version 0.22.0. Furthermore, I tested out the 0.23.dev0 version as well and the issue is still present.

Platform:      Windows-10-10.0.18362-SP0
Python:        3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
Executable:    C:\Users\angjw\anaconda3\envs\mne\python.exe
CPU:           Intel64 Family 6 Model 142 Stepping 12, GenuineIntel: 8 cores
Memory:        7.8 GB

mne:           0.23.dev0
numpy:         1.19.1 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.5.0
matplotlib:    3.2.2 {backend=Qt5Agg}

sklearn:       0.23.1
numba:         0.50.1
nibabel:       3.1.1
nilearn:       0.6.2
dipy:          1.1.1
cupy:          Not found
pandas:        1.0.5
mayavi:        4.7.2.dev0
pyvista:       0.25.3 {pyvistaqt=0.1.1, OpenGL 4.5.0 NVIDIA 457.63 via GeForce MX250/PCIe/SSE2}
vtk:           9.0.1
PyQt5:         5.11.2

**Comment by drammock** [comment] 2021-04-20 14:14
duplicate of #9125

**Closed by drammock** 2021-04-20 14:14 UTC
Labels: BUG
